import { BuilderNavbar } from '@/components/Builder/BuilderNavbar'
import '../styles/globals.css'
import type { AppProps } from 'next/app'
import NextNProgress from 'nextjs-progressbar'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { AuthProvider } from '@/contexts/auth'
import { Toaster } from 'react-hot-toast'
import { Navbar } from '@/components/Common/Navbar'

export default function App({ Component, pageProps }: AppProps) {
    const router = useRouter()
    const routeName = router.asPath
        .split('/')
        .pop()!
        .split('-')
        .join(' ')
        .toString()

    const title = routeName.charAt(0).toUpperCase() + routeName.slice(1)

    return (
        <>
            <Head>
                <title>{title ? title : 'Resume It'}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link
                    rel="icon"
                    href="/favicon.ico"
                />
            </Head>
            <AuthProvider>
                <Toaster />
                <NextNProgress options={{ showSpinner: false }} />
                {router.pathname.includes('/builder') ? null : <Navbar />}
                <Component {...pageProps} />
            </AuthProvider>
        </>
    )
}
